services:
  postgres:
    container_name: stream-archivist-tracker-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5434:5432'