global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway-service:8080']

  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'auth-service:8081']

  - job_name: 'tracker-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'tracker-service:8082']

  - job_name: 'storage-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['storage-service:8083']

  - job_name: 'recording-orchestrator-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['recording-orchestrator-service:8084']

  - job_name: 'recording-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['recording-worker:8085']

  - job_name: 'uploading-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['uploading-worker:8086']

  - job_name: 'subscription-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['subscription-service:8087']

  - job_name: 'auth-postgres-exporter'
    static_configs:
      - targets: ['auth-postgres-exporter:9187']

  - job_name: 'tracker-postgres-exporter'
    static_configs:
      - targets: ['tracker-postgres-exporter:9187']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'minio-cluster-exporter'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'minio-node-exporter'
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets: [ 'minio:9000' ]

  - job_name: 'minio-bucket-exporter'
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets: [ 'minio:9000' ]