name: Build auth-service
on:
  push:
    paths:
      - 'auth-service/**'
      - 'pom.xml'
      - '.github/workflows/**'
    branches-ignore: [ "main" ]
  pull_request:
    paths:
      - 'auth-service/**'
      - 'pom.xml'
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build root POM
        run: mvn -f pom.xml clean install -DskipTests

      - name: Build common module
        run: mvn -f common/pom.xml clean install -DskipTests

      - name: Build auth-service
        working-directory: ./auth-service
        run: mvn clean package -DskipTests