name: Build and test recording-orchestrator
on:
  push:
    paths:
      - 'recording-orchestrator-service/**'
      - 'common/**'
      - 'pom.xml'
      - '.github/workflows/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'recording-orchestrator-service/**'
      - 'common/**'
      - 'pom.xml'
      - '.github/workflows/**'
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build root POM
        run: mvn -f pom.xml clean install -DskipTests

      - name: Build common module
        run: mvn -f common/pom.xml clean install -DskipTests

      - name: Build recording-orchestrator
        working-directory: ./recording-orchestrator-service
        run: mvn clean package -DskipTests

      - name: Run tests
        working-directory: ./recording-orchestrator-service
        run: mvn -B verify
